### ISSUE TITLE
Should Ufixed be changed to UFixed in light of the recent Julia rename?

### ISSUE THREAD

**Issue by ivarne** [JeffBezanson/FixedPointNumbers.jl#16]
A recent PR in Julia changed the capitalization of the unsigned integers, so that they are written `UInt` instead of `Uint`. That naming convention might apply here also.

**Comment by vchuravy** [comment]
I would support that I found myself writing UFixed quite often.

**Comment by ssfrr** [comment]
I believe this is done and can be closed now.
