### ISSUE TITLE
Convert for arrays

### ISSUE THREAD

**Issue by Jakki42** [JeffBezanson/FixedPointNumbers.jl#20]
x=rand(Float32,100,100)

julia> convert(Ufixed16,x)
*ERROR: `convert` has no method matching convert(::Type{UfixedBase{Uint16,16}}, ::Array{Float32,2})
 in convert at base.jl:13*

However:

julia> convert(Ufixed16,x[1,1])
*Ufixed16(0.31148)*

I am new to Julia, so may I'm just doing something wrong?

**Comment by timholy** [comment]
Try `convert(Array{Ufixed16}, x)`. The point being that you can't convert an entire array to a single number, which is what a `Ufixed16` is. But you can convert it to an array of `Ufixed16`.

In specific cases you might imagine it's possible to read your mind and guess what you really intended, but that often becomes a source of trouble. For example, how would you handle an array of arrays?

**Comment by Jakki42** [comment]
Thank you - the curly braces are a bit scary (which is odd, since I have a background in K&R C long time ago) and I just keep forgetting this syntax all the time :-)
`convert(Array{Ufixed16},x)` worked beautifully! Maybe I'll learn this someday :-)
