### ISSUE TITLE
Ufixed8(0xff) isn't Ufixed8(1.0)

### ISSUE THREAD

**Issue by yakir12** [JeffBezanson/FixedPointNumbers.jl#21]
```Julia 
julia> Ufixed8(0xff)
Ufixed8(0.004)
```
Isn't it supposed to be Ufixed8(1.0)?
```Julia 
Julia Version 0.4.0-dev+4791
Commit a9b0135 (2015-05-12 15:32 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
`julia runtests.jl` completed without any errors though..?

**Comment by timholy** [comment]
You're being tripped up by the difference between conversion and reinterpretation:
```jl
julia> Ufixed8(0xff)
Ufixed8(0.004)

julia> reinterpret(Ufixed8, 0xff)
Ufixed8(1.0)

julia> 0xffuf8
Ufixed8(1.0)
```
On julia 0.4, we should probably have `Ufixed8(0xff)` throw an error, since 255 is not representable as a Ufixed8 (it's still using the old julia 0.3 "unsafe conversion" convention).

**Comment by yakir12** [comment]
Ah, I see. I'll try and watch out for that. That settles that then.
Thanks!
