### ISSUE TITLE
Conversion between UFixed and UInt

### ISSUE THREAD

**Issue by vchuravy** [JeffBezanson/FixedPointNumbers.jl#38]
@timholy  is this intended behaviour?

current master
```julia
convert(UFixed8,0xff) = UFixed8(0.004)
convert(UFixed8,0x00) = UFixed8(0.0)
convert(UFixed8,0x01) = UFixed8(1.0)
reinterpret(UFixed8,0xff) = UFixed8(1.0)
reinterpret(UFixed8,0x00) = UFixed8(0.0)
reinterpret(UFixed8,0x01) = UFixed8(0.004)
```

Thinking I might have broken that I looked at a previous commit
at bb3dee7
```julia
convert(UFixed8,0xff) = Ufixed8(0.004)
convert(UFixed8,0x00) = Ufixed8(0.0)
convert(UFixed8,0x01) = Ufixed8(1.0)
reinterpret(UFixed8,0xff) = Ufixed8(1.0)
reinterpret(UFixed8,0x00) = Ufixed8(0.0)
reinterpret(UFixed8,0x01) = Ufixed8(0.004)
````

**Comment by timholy** [comment]
That behavior is actually a failure of checked conversions for unsigned inputs (I seem to remember noting a julia issue about this recently). What you're actually asking for is
```
convert(UFixed8, 255)
```
and 255 isn't representable using numbers that range from 0 to 1. But for some reason julia does not throw an `InexactError` as it should, so you're getting the equivalent of `255 % UFixed8` (which hasn't been defined, but 0.004 is indeed what you should get from that computation).

What you're probably looking for is
```jl
julia> 0xffuf8
UFixed8(1.0)
```
or
```jl
julia> UFixed8(0xff, 0)
UFixed8(1.0)
```

**Comment by vchuravy** [comment]
Ah right :)
